# Generated by Django 4.0 on 2022-04-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_skattekonto_client_name_tinglysning_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinglysning',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
