# Generated by Django 4.0 on 2022-04-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_tinglysning_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinglysning',
            name='concern',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tinglysning',
            name='date_serial',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tinglysning',
            name='document_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tinglysning',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tinglysning',
            name='tinglysning',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
