# Generated by Django 4.0 on 2022-04-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_tinglysning_concern_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vatpastrecord',
            name='filling_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
