# Generated by Django 4.0 on 2022-04-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_vatpastrecord_filling_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vatcurrent',
            name='filling_deadline',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
