# Generated by Django 4.0 on 2022-04-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_vatcurrent_filling_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='eindkomst',
            name='client_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxreturn',
            name='client_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
