# Generated by Django 4.0 on 2022-04-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_eindkomst_client_name_taxreturn_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountstatement',
            name='client_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountstatus',
            name='client_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientassignment',
            name='client_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dividends',
            name='client_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vatcurrent',
            name='client_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
