# Generated by Django 4.0 on 2022-04-18 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_accountstatement_client_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vatcurrent',
            old_name='filling_deadline',
            new_name='filing_deadline',
        ),
    ]
