# Generated by Django 4.0 on 2022-04-18 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_filling_deadline_vatcurrent_filing_deadline'),
    ]

    operations = [
    ]
