# Generated by Django 4.0 on 2022-04-18 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_merge_20220418_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vatcurrent',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vatcurrent',
            name='client_name',
            field=models.CharField(max_length=255),
        ),
    ]
