# Generated by Django 4.0 on 2022-04-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_vatcurrent_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vatcurrent',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
