# Generated by Django 4.0 on 2022-04-18 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_vatcurrent_client_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vatpastrecord',
            old_name='filling_date',
            new_name='filing_deadline',
        ),
    ]
