# Generated by Django 4.0 on 2022-04-18 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_filling_date_vatpastrecord_filing_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vatpastrecord',
            old_name='filing_deadline',
            new_name='filling_date',
        ),
    ]
