# Generated by Django 4.0 on 2022-04-20 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_vatcurrent_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountstatus',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='VatAccountInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('cvr', models.CharField(db_index=True, max_length=255)),
                ('client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_id', models.CharField(max_length=255)),
                ('refund_limit', models.IntegerField(default=0)),
                ('phone_number', models.CharField(max_length=255)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.client')),
            ],
            options={
                'db_table': 'vataccountinfo',
                'ordering': ('-created_at',),
            },
        ),
    ]
