# Generated by Django 4.0 on 2022-04-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_vataccountinfo_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vatcurrent',
            name='filing_deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
