# Generated by Django 4.0 on 2022-04-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_virkinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virkinfo',
            name='email',
            field=models.EmailField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
