# Generated by Django 4.0 on 2022-04-21 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_vatpastrecord_client_responsible_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vatpastrecord',
            old_name='filling_date',
            new_name='filing_deadline',
        ),
        migrations.AlterField(
            model_name='vatpastrecord',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.client'),
        ),
    ]
