# Generated by Django 4.0 on 2022-04-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_vatpastrecord_filing_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vatpastrecord',
            name='scrape_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
