# Generated by Django 4.0 on 2022-04-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_vatpastrecord_scrape_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vatcurrent',
            name='client_responsible_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
