# Generated by Django 4.0 on 2022-04-21 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_vatcurrent_client_responsible_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dividends',
            name='client_responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user'),
        ),
        migrations.AddField(
            model_name='dividends',
            name='client_responsible_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eindkomst',
            name='client_responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user'),
        ),
        migrations.AddField(
            model_name='eindkomst',
            name='client_responsible_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='skattekonto',
            name='client_responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user'),
        ),
        migrations.AddField(
            model_name='skattekonto',
            name='client_responsible_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tinglysning',
            name='client_responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user'),
        ),
        migrations.AddField(
            model_name='tinglysning',
            name='client_responsible_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
