# Generated by Django 4.0 on 2022-04-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_dividends_client_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vataccountinfo',
            name='refund_limit',
            field=models.CharField(max_length=255),
        ),
    ]
