# Generated by Django 4.0 on 2022-06-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_vatpastrecord_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vatpastrecord',
            name='filing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
