# Generated by Django 4.0 on 2022-06-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_vatpastrecord_filing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vatpastrecord',
            name='date_filing',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
