# Generated by Django 4.0 on 2022-06-03 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_vatpastrecord_date_filing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vatpastrecord',
            name='date_filing',
        ),
    ]
