# Generated by Django 4.0 on 2022-06-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_remove_vatpastrecord_date_filing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vatpastrecord',
            name='filing_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
