# Generated by Django 4.0 on 2022-06-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_vatpastrecord_filing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vatpastrecord',
            name='filing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
